import type { MemberDues, MonthDues, MonthDuesStatus, SemesterDuesSummary } from '@/components/dues/types';

function month(status: MonthDuesStatus, description: string): MonthDues {
  return { status, description };
}

const paid = (description = '완료') => month('paid', description);
const exempt = (description: string) => month('exempt', description);
const unpaid = (description: string) => month('unpaid', description);
const notApplicable = () => month('not-applicable', '납부 비대상');

export const SEMESTER_DUES_SUMMARIES: SemesterDuesSummary[] = [
  {
    id: '2026-2',
    shortLabel: '26년 2학기',
    title: '2026년 2학기 회비',
    totalMembers: 12,
    exemptMembers: 5,
    targetMembers: 7,
    completedMembers: 6,
    unpaidMembers: 4,
    totalAmount: 510000,
    paidAmount: 460000,
    unpaidAmount: 65000,
    needsReview: true,
  },
  {
    id: '2026-1',
    shortLabel: '26년 1학기',
    title: '2026년 1학기 회비',
    totalMembers: 10,
    exemptMembers: 1,
    targetMembers: 10,
    completedMembers: 9,
    unpaidMembers: 0,
    totalAmount: 540000,
    paidAmount: 540000,
    unpaidAmount: 0,
    needsReview: false,
  },
  {
    id: '2025-2',
    shortLabel: '25년 2학기',
    title: '2025년 2학기 회비',
    totalMembers: 8,
    exemptMembers: 0,
    targetMembers: 8,
    completedMembers: 7,
    unpaidMembers: 1,
    totalAmount: 480000,
    paidAmount: 470000,
    unpaidAmount: 10000,
    needsReview: false,
  },
];

export const DUES_MONTHS = ['9월', '10월', '11월', '12월', '1월', '2월'];

export const CURRENT_SEMESTER_MEMBERS: MemberDues[] = [
  {
    id: 'member-yuna',
    name: '최유나',
    studentNumber: '2022174077',
    track: 'Backend',
    months: [paid('70,000원 입금 중 10,000원 배분'), paid(), paid(), paid(), paid(), paid()],
    status: 'overpaid',
    assessedAmount: 60000,
    paidAmount: 60000,
    unpaidAmount: 0,
    excessAmount: 10000,
    refundStatus: 'partial',
    refundAmount: 10000,
    refundReason: '초과 납부',
  },
  {
    id: 'member-jihoon',
    name: '오지훈',
    studentNumber: '2024174088',
    track: 'Game',
    months: Array.from({ length: 6 }, notApplicable),
    status: 'exempt',
    assessedAmount: null,
    paidAmount: null,
    unpaidAmount: null,
    refundStatus: 'none',
  },
  {
    id: 'member-doyun',
    name: '김도윤',
    studentNumber: '2024174065',
    track: 'iOS',
    months: [paid('60,000원 일시납 배분'), paid(), paid(), paid(), paid(), paid()],
    status: 'paid',
    assessedAmount: 60000,
    paidAmount: 60000,
    unpaidAmount: 0,
    refundStatus: 'none',
  },
  {
    id: 'member-seojun',
    name: '박서준',
    studentNumber: '2023174052',
    track: 'Backend',
    months: [paid('1차 30,000원 배분'), paid(), paid(), paid('2차 30,000원 배분'), paid(), paid()],
    status: 'paid',
    assessedAmount: 60000,
    paidAmount: 60000,
    unpaidAmount: 0,
    refundStatus: 'none',
  },
  {
    id: 'member-haneul',
    name: '이하늘',
    studentNumber: '2023174011',
    track: 'Frontend',
    months: [paid(), paid(), paid(), paid(), paid(), unpaid('부족 납부 5,000원(10,000원 중)')],
    status: 'partial',
    assessedAmount: 60000,
    paidAmount: 55000,
    unpaidAmount: 5000,
    refundStatus: 'none',
  },
  {
    id: 'member-hangyeol',
    name: '정한결',
    studentNumber: '2022174130',
    track: 'Frontend',
    months: [
      exempt('Frontend 트랙장 2026.09~11'),
      exempt('Frontend 트랙장'),
      exempt('Frontend 트랙장'),
      paid(),
      paid(),
      paid(),
    ],
    status: 'paid',
    assessedAmount: 30000,
    paidAmount: 30000,
    unpaidAmount: 0,
    refundStatus: 'none',
  },
  {
    id: 'member-somi',
    name: '한소미',
    studentNumber: '2021174093',
    track: 'Backend',
    months: [paid(), paid(), paid(), exempt('탈퇴 2026.12~계속'), exempt('탈퇴'), exempt('탈퇴')],
    status: 'overpaid',
    assessedAmount: 30000,
    paidAmount: 40000,
    unpaidAmount: 0,
    excessAmount: 10000,
    refundStatus: 'needed',
    refundAmount: 10000,
    refundReason: '탈퇴 기간',
  },
  {
    id: 'member-mentor',
    name: '서지훈',
    studentNumber: '2022174044',
    track: 'Design',
    months: Array.from({ length: 6 }, (_, index) => exempt(index === 0 ? '멘토 2024.09~계속' : '멘토')),
    status: 'exempt',
    assessedAmount: 0,
    paidAmount: 0,
    unpaidAmount: 0,
    refundStatus: 'completed',
  },
  {
    id: 'member-minjun',
    name: '김민준',
    studentNumber: '2024174007',
    track: 'Android',
    months: [paid(), paid(), paid(), paid(), unpaid('부족 납부 3,000원'), unpaid('연결된 기록 없음')],
    status: 'unpaid',
    assessedAmount: 60000,
    paidAmount: 43000,
    unpaidAmount: 20000,
    refundStatus: 'none',
  },
  {
    id: 'member-seoyeon',
    name: '이서연',
    studentNumber: '2024174101',
    track: 'PM',
    months: [paid(), paid(), paid(), paid(), paid(), unpaid('연결된 기록 없음')],
    status: 'unpaid',
    assessedAmount: 60000,
    paidAmount: 50000,
    unpaidAmount: 10000,
    refundStatus: 'none',
  },
  {
    id: 'member-jian',
    name: '박지안',
    studentNumber: '2023174090',
    track: 'Data Analyst',
    months: [
      paid(),
      paid(),
      paid(),
      unpaid('연결된 기록 없음'),
      unpaid('연결된 기록 없음'),
      unpaid('연결된 기록 없음'),
    ],
    status: 'unpaid',
    assessedAmount: 60000,
    paidAmount: 30000,
    unpaidAmount: 30000,
    refundStatus: 'none',
  },
  {
    id: 'member-taeo',
    name: '강태오',
    studentNumber: '2024174210',
    track: 'Backend',
    months: [
      exempt('부트캠프(소프티어) 2026.09~11'),
      exempt('부트캠프(소프티어)'),
      exempt('부트캠프(소프티어)'),
      paid(),
      paid(),
      paid(),
    ],
    status: 'paid',
    assessedAmount: 30000,
    paidAmount: 30000,
    unpaidAmount: 0,
    refundStatus: 'none',
  },
  {
    id: 'member-seoa',
    name: '윤서아',
    studentNumber: '2023174300',
    track: 'iOS',
    months: Array.from({ length: 6 }, (_, index) => exempt(index === 0 ? '졸업 2026.09~계속' : '졸업')),
    status: 'exempt',
    assessedAmount: 0,
    paidAmount: 0,
    unpaidAmount: 0,
    refundStatus: 'none',
  },
];

export function getSemesterMembers(semesterId: string): MemberDues[] {
  if (semesterId === '2026-2') return CURRENT_SEMESTER_MEMBERS;

  if (semesterId === '2026-1') {
    return CURRENT_SEMESTER_MEMBERS.slice(0, 10).map((member, index) => ({
      ...member,
      months: Array.from({ length: 6 }, () => (index === 9 ? exempt('예외') : paid())),
      status: index === 9 ? 'exempt' : 'paid',
      assessedAmount: index === 9 ? 0 : 60000,
      paidAmount: index === 9 ? 0 : 60000,
      unpaidAmount: 0,
      excessAmount: undefined,
      refundStatus: 'none',
      refundAmount: undefined,
      refundReason: undefined,
    }));
  }

  return CURRENT_SEMESTER_MEMBERS.slice(0, 8).map((member, index) => ({
    ...member,
    months: Array.from({ length: 6 }, (_, monthIndex) =>
      index === 7 && monthIndex === 5 ? unpaid('미납 · 연결된 기록 없음') : paid(),
    ),
    status: index === 7 ? 'unpaid' : 'paid',
    assessedAmount: 60000,
    paidAmount: index === 7 ? 50000 : 60000,
    unpaidAmount: index === 7 ? 10000 : 0,
    excessAmount: undefined,
    refundStatus: 'none',
    refundAmount: undefined,
    refundReason: undefined,
  }));
}
