import type { ImportDuesMatch, ImportTransaction } from '@/components/ledger/import/types';

export const IMPORT_DUES_MATCHES: ImportDuesMatch[] = [
  {
    memberId: 'member-minjun',
    memberName: '김민준',
    studentNumber: '2024174007',
    track: 'Android',
    semester: '2026년 2학기',
    requiredAmount: 60000,
  },
  {
    memberId: 'member-seoyeon',
    memberName: '이서연',
    studentNumber: '2024174101',
    track: 'PM',
    semester: '2026년 2학기',
    requiredAmount: 60000,
  },
  {
    memberId: 'member-jian',
    memberName: '박지안',
    studentNumber: '2023174090',
    track: 'Data Analyst',
    semester: '2026년 2학기',
    requiredAmount: 60000,
  },
  {
    memberId: 'member-somi',
    memberName: '한소미',
    studentNumber: '2021174093',
    track: 'Backend',
    semester: '2026년 2학기',
    requiredAmount: 30000,
    refundReason: '탈퇴 기간',
    refundAmount: 10000,
  },
];

export function createInitialImportTransactions(): ImportTransaction[] {
  return [
    {
      id: 'import-001',
      occurredAt: '2026-11-16T09:10',
      type: 'deposit',
      counterparty: '김민준',
      amount: 40000,
      selected: true,
      category: '회비',
      duesMatchId: 'member-minjun',
      note: '',
      evidences: [],
    },
    {
      id: 'import-002',
      occurredAt: '2026-11-17T18:22',
      type: 'deposit',
      counterparty: '이서연',
      amount: 10000,
      selected: true,
      category: '회비',
      duesMatchId: 'member-seoyeon',
      note: '',
      evidences: [],
    },
    {
      id: 'import-003',
      occurredAt: '2026-11-18T08:40',
      type: 'withdrawal',
      counterparty: '박지안',
      amount: 15000,
      selected: true,
      category: '기타',
      duesMatchId: null,
      note: '',
      evidences: [],
    },
    {
      id: 'import-004',
      occurredAt: '2026-11-18T08:41',
      type: 'withdrawal',
      counterparty: '한소미',
      amount: 10000,
      selected: true,
      category: '회비 반환',
      duesMatchId: 'member-somi',
      note: '',
      evidences: [],
    },
  ];
}
